version: '3.9'

services:
  api:
    build:
      context: ../..
      dockerfile: infra/docker/Dockerfile.api
    working_dir: /app
    command: uvicorn backend.api.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - PYTHONPATH=/app
    volumes:
      - ../../backend:/app/backend
      - ../../backend/data/sample_data:/app/backend/data/sample_data
    ports:
      - '8000:8000'

  ui:
    build:
      context: ../..
      dockerfile: infra/docker/Dockerfile.ui
    working_dir: /app
    environment:
      - VITE_API_URL=http://api:8000
    command: npm run dev -- --host 0.0.0.0 --port 5173
    volumes:
      - ../../frontend:/app
      - ui_node_modules:/app/node_modules
    ports:
      - '5173:5173'
    depends_on:
      - api

volumes:
  ui_node_modules: